### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by whysosaket**

### CODE REVIEW

**Comment by iamsahebgiri** [comment]
@whysosaket looks like you have merge conflicts. Look into it.

**Comment by whysosaket** [comment]
wait

**Comment by whysosaket** [comment]
> @whysosaket looks like you have merge conflicts. Look into it.

@iamsahebgiri Preview Deployment looks fine to me...idk what the conflict is

**Comment by iamsahebgiri** [comment]
```
components/sponsor.tsx
public/community/Ascent_Academy.png
seed.ts
yarn.lock
```

Look these files too

**Pull request closed without merging**
